# Generated by Django 3.1.14 on 2025-10-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitBook',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.basemodel')),
                ('book_name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=255, unique=True)),
                ('md_file_name', models.CharField(max_length=100)),
                ('tag', models.ManyToManyField(blank=True, to='articles.Tag')),
            ],
            bases=('articles.basemodel',),
        ),
    ]
