# Generated by Django 3.1.14 on 2025-10-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.basemodel')),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=('articles.basemodel',),
        ),
    ]
