# Generated by Django 3.1.14 on 2025-10-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('content', models.TextField(default='', null=True)),
                ('click_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_content', models.CharField(help_text='请输入要搜索的内容', max_length=100)),
                ('search_choice', models.CharField(choices=[('all', 'All'), ('gitbooks', 'Gitbooks'), ('articles', 'Articles'), ('journals', 'Journals'), ('code', 'Code')], help_text='请选择要查询的范围', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.basemodel')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ManyToManyField(blank=True, to='articles.Tag')),
            ],
            options={
                'ordering': ['-update_time'],
            },
            bases=('articles.basemodel',),
        ),
    ]
