name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIV_KEY }}
      - name: deploy
      - run: ssh watch@${{secrets.SERVER_IP}} "cd /home/watch/sites && bash update_sites.sh"
