name: Django CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r virtual/requirements.txt
    - name: Prepare Databases
      run: |
        python my_blog/manage.py makemigrations --noinput
        python my_blog/manage.py migrate --noinput
    - name: Run Tests - app_life_summary
      run: |
        python my_blog/manage.py test app_life_summary
    - name: Run Tests - app_timeline
      run: |
        python my_blog/manage.py test app_timeline
    - name: Run Tests - weixin
      run: |
        python my_blog/manage.py test weixin
    - name: Run Tests - log_file_deal
      run: |
        python my_blog/manage.py test log_file_deal
    - name: Run Tests - articles
      run: |
        python my_blog/manage.py test articles
    - name: Run Tests - code_collect
      run: |
        python my_blog/manage.py test code_collect
    - name: Run Tests - toolhub
      run: |
        python my_blog/manage.py test toolhub
    - name: Run Tests - common_module
      run: |
        python my_blog/manage.py test common_module
    - name: Run Tests - gitbook_notes
      run: |
        python my_blog/manage.py test gitbook_notes
    - name: Run Tests - work_journal
      run: |
        python my_blog/manage.py test work_journal
    - name: Run Tests - just_eating
      run: |
        python my_blog/manage.py test just_eating
    - name: Run Tests - homepage
      run: |
        python my_blog/manage.py test homepage
