name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.4.10, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r virtual/requirements.txt
    - name: Run Tests - app_life_summary
      run: |
        python manage.py test app_life_summary
    - name: Run Tests - app_timeline
      run: |
        python manage.py test app_timeline
    - name: Run Tests - weixin
      run: |
        python manage.py test weixin
    - name: Run Tests - log_file_deal
      run: |
        python manage.py test log_file_deal
    - name: Run Tests - articles
      run: |
        python manage.py test articles
    - name: Run Tests - code_collect
      run: |
        python manage.py test code_collect
    - name: Run Tests - toolhub
      run: |
        python manage.py test toolhub
    - name: Run Tests - common_module
      run: |
        python manage.py test common_module
    - name: Run Tests - functional_tests
      run: |
        python manage.py test functional_tests
    - name: Run Tests - gitbook_notes
      run: |
        python manage.py test gitbook_notes
    - name: Run Tests - work_journal
      run: |
        python manage.py test work_journal
    - name: Run Tests - just_eating
      run: |
        python manage.py test just_eating
